name: meins_core
version: 1.2
main: de.ender.core.Main
api-version: 1.19
load: STARTUP
authors: [ ender__exe ]
description: Core of Meins
website: https://github.com/github-dotEXE

commands:
  afk:
    description: toggles afk