name: meins_core
version: '${project.version}'
main: de.ender.core.Main
api-version: 1.19
load: STARTUP
authors: [ ender__exe ]
description: Core of Meins
website: https://github.com/github-dotEXE

commands:
  afk:
    description: toggles afk
  customitems:
    description: /customitems [name]
  floattext:
    description: places a floating text in the world
  update:
    description: update plugin command